name: Generate BINGO Image

on:
  push:
    branches:
      - main

jobs:
  generate-bingo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run BINGO Script
      run: python bingo.py

    - name: Upload BINGO Image
      uses: actions/upload-artifact@v3
      with:
        name: bingo-image
        path: bingo.png
