name: Release BINGO Images

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every 30 seconds
  workflow_dispatch:

jobs:
  release-bingo:
    runs-on: ubuntu-latest

    steps:
    - name: Download Cached Images
      uses: actions/cache@v3
      with:
        path: cache
        key: bingo-images-cache

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-bingo-${{ github.run_number }}
        release_name: "BINGO Images Release ${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Release 2 Images
      run: |
        mkdir -p release
        images=$(ls cache | head -n 2) # Select the first 2 images
        for image in $images; do
          mv "cache/$image" "release/$image"
          echo "Released $image"
        done

    - name: Upload Each Image
      run: |
        for file in release/*; do
          echo "Uploading $file"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: image/png" \
            --data-binary @"$file" \
            ${{ steps.create_release.outputs.upload_url }}?name=$(basename $file)
        done

    - name: Clean Up
      run: |
        rm -rf release
        if [ "$(ls -A cache)" ]; then
          echo "Cache still has images."
        else
          echo "Cache is empty. Triggering regeneration workflow..."
        fi
